name: wireguard-go

on: 
  release:
    types: [published]
  push:
    branches: 
      - main
  schedule:
    - cron: 0 0,6,12,18 * * *

# env:

  
jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Prerequisites
        run: |
          sudo -E apt install golang -y
          git clone https://git.zx2c4.com/wireguard-go
          cd wireguard-go
          go build -v -o "wireguard-go"
          mkdir bin
          cp wireguard-go bin/
          
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: wireguard-go
          path: wireguard-go/bin/
